### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by andybak** [ryanslikesocool/TextureTools#1]
Whilst I applaud the sentiment, this means that potential users probably fall into one of two types:

1. People who can't use it
2. People who use it because they haven't thought through the implications

The users you hope to prevent using this are a very small group and are the group that can probably trivially afford to reimplement this.

However - the biggest problem is that you've used a non-open-source licence. This means that it's incompatible with projects that use recognised licences.

I'd love to use your stuff with Open Brush - a non-profit, open source, community led project (I presume this ticks all of your boxes) but I simply can't because of the legal risks and issues around mixing open source licences with non-open-source licences.

I really hope you'll seek advice on this topic. There is hopefully a way to achive some of your goals with less collateral damage.

I wish you all the best.

**Comment by ryanslikesocool** [comment]
Thanks for the input!  I don't understand legalese very well so I didn't realize the license could potentially cause a lot of problems.  I'm currently searching for a new one that would be a better fit (or I might just revert back to the original MIT license).  Did you have one in mind that might be better suited?

**Comment by ryanslikesocool** [comment]
The license is back to MIT with v1.2.2.  Sorry for any inconvenience!

**Comment by andybak** [comment]
Hi. Sorry I didn't reply sooner. There is potentially a very interesting (and possibly lengthy) conversation to be had on this topic but I had a ton of other things battling for my time. Some other day maybe.

All the best.
